Offset boolean column in carton_to_target
sdss/sdssdb pull request #122
Opened 2022-05-19 19:12 UTC by imedan

@albireox , I added the offset boolean column to the carton_to_target table. One question before merging is I set the default value to False (which seemed reasonable) in the python class, but is there a similar kind of setting for this in targetdb.sql? Sorry I am not as familiar with that latter file.

2022-05-19 21:10 UTC, albireox requested changes

2022-05-19 21:10 UTC, albireox commented on schema/sdss5db/targetdb/targetdb.sql
> +    offset BOOLEAN,
I think you want to do this `offset BOOLEAN DEFAULT false,`

2022-05-19 21:10 UTC, albireox commented
I added a comment about the default value in PSQL. The rest looks good.

2022-05-20 14:42 UTC, imedan commented
perfect, just changed that line in targetdb.sql then

2022-05-20 14:44 UTC, imedan commented
should I merge to main?

2022-05-20 16:06 UTC, albireox approved these changes

2022-05-20 16:06 UTC, albireox commented
Yes, go ahead!

2022-05-20 16:13 UTC, merged